name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: "./KIBER RUSSIA"
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: "./KIBER RUSSIA"
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kiber-russia-launcher
        path: "KIBER RUSSIA/app/build/outputs/apk/debug/app-debug.apk"
